version: '3.8'
services:
  nest-api:
    container_name: nest-api
    image: node:14
    working_dir: /app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    links:
      - postgres:postgres
    command: sh -c 'npm run start:dev'
    env_file:
      - .env
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: link
      POSTGRES_PASSWORD: knil
      POSTGRES_DB: linkdb
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db
