POST http://localhost:3000/user
Content-type: application/json

{
  "firstName": "teste",
  "lastName": "teste",
  "email": "teste@email.com",
  "password": "123",
  "phone": "+55 (41) 99999-9999",
  "mobile": "+55 (41) 99999-9999",
  "registry": "012.123.123-12",
  "creci": "12.123-BR",
  "birthday": "1999-01-08",
  "permissionLevel": ""
}

###

GET http://localhost:3000/user

###

GET http://localhost:3000/user/c8b428ac-8bca-4608-b54f-40b6f4b84b81


###

PATCH http://localhost:3000/user/
Content-Type: application/json

{
  "firstName": "teste",
  "lastName": "teste",
  "permissionLevel": "d1fa1d82-defa-4b98-86b6-86c86bcbd6d2"
}

###

DELETE http://localhost:3000/user/65e046df-7e70-4c0f-bf31-7d5b3a732b2d

###

POST http://localhost:3000/user/login
Content-type: application/json

{
  "username": "teste@email.com",
  "password": "123"
}

###

PUT http://localhost:3000/token/refresh
Content-type: application/json

{
  "oldToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlQGVtYWlsLmNvbSIsInN1YiI6ImM4YjQyOGFjLThiY2EtNDYwOC1iNTRmLTQwYjZmNGI4NGI4MSIsImlhdCI6MTYzNjQ5MzkxMSwiZXhwIjoxNjM2NDkzOTcxfQ.867sTNPurlfW3ZkjbyqMnzY3_SxRvnJIyaATXzsk154"
}